-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 17, 2020 at 03:13 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Bomberman`
--

-- --------------------------------------------------------

--
-- Table structure for table `Adventure`
--

CREATE TABLE `Adventure` (
  `username` varchar(255) NOT NULL,
  `stage` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `Stages`
--

CREATE TABLE `Stages` (
  `id_stage` int(11) NOT NULL,
  `grid` text NOT NULL,
  `creeps` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `Stages`
--

INSERT INTO `Stages` (`id_stage`, `grid`, `creeps`) VALUES
(1, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"flame_powerup_hidden\", \"box\", \"box\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"bomb_powerup_hidden\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\", \"box\", \"block\"], [\"block\", \"bomb_powerup_hidden\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"box\", \"portal_hidden\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[7, 12], [6, 13], [7, 13]]'),
(2, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"portal_hidden\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"flame_powerup_hidden\", \"flame_powerup_hidden\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"flame_powerup_hidden\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[13, 10], [9, 8], [6, 13]]'),
(3, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"flame_powerup_hidden\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"bomb_powerup_hidden\", \"bomb_powerup_hidden\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"portal_hidden\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"flame_powerup_hidden\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[11, 8], [11, 11], [8, 11]]'),
(4, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"box\", \"box\", \"box\", \"flame_powerup_hidden\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"portal_hidden\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"flame_powerup_hidden\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[6, 7], [8, 9], [12, 7]]'),
(5, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"portal_hidden\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"bomb_powerup_hidden\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[11, 13], [11, 8], [9, 11]]'),
(6, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"flame_powerup_hidden\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"bomb_powerup_hidden\", \"box\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"bomb_powerup_hidden\", \"box\", \"flame_powerup_hidden\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"ground\", \"portal_hidden\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[8, 13], [12, 11], [6, 11]]'),
(7, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"portal_hidden\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"bomb_powerup_hidden\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"box\", \"box\", \"bomb_powerup_hidden\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[9, 11], [8, 11], [11, 13]]'),
(8, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"portal_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"flame_powerup_hidden\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"box\", \"flame_powerup_hidden\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"flame_powerup_hidden\", \"box\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"flame_powerup_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"flame_powerup_hidden\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"flame_powerup_hidden\", \"flame_powerup_hidden\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[9, 11], [7, 12], [9, 12]]'),
(9, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"portal_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"flame_powerup_hidden\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"bomb_powerup_hidden\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"flame_powerup_hidden\", \"block\", \"ground\", \"block\", \"flame_powerup_hidden\", \"block\", \"bomb_powerup_hidden\", \"block\", \"bomb_powerup_hidden\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"flame_powerup_hidden\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"flame_powerup_hidden\", \"box\", \"flame_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"bomb_powerup_hidden\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"flame_powerup_hidden\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"bomb_powerup_hidden\", \"box\", \"bomb_powerup_hidden\", \"flame_powerup_hidden\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[11, 13], [10, 13], [7, 9]]'),
(10, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"box\", \"box\", \"box\", \"flame_powerup_hidden\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"bomb_powerup_hidden\", \"block\", \"bomb_powerup_hidden\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"flame_powerup_hidden\", \"block\", \"ground\", \"block\"], [\"block\", \"flame_powerup_hidden\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"flame_powerup_hidden\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"portal_hidden\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"bomb_powerup_hidden\", \"block\"], [\"block\", \"ground\", \"flame_powerup_hidden\", \"bomb_powerup_hidden\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]', '[[11, 8], [6, 13], [8, 13]]');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Adventure`
--
ALTER TABLE `Adventure`
  ADD PRIMARY KEY (`username`);

--
-- Indexes for table `Stages`
--
ALTER TABLE `Stages`
  ADD PRIMARY KEY (`id_stage`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Stages`
--
ALTER TABLE `Stages`
  MODIFY `id_stage` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
