-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Mar 04, 2020 at 07:11 AM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Bomberman`
--

-- --------------------------------------------------------

--
-- Table structure for table `Stages`
--

CREATE TABLE `Stages` (
  `id_stage` int(11) NOT NULL,
  `grid` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `Stages`
--

INSERT INTO `Stages` (`id_stage`, `grid`) VALUES
(1, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(2, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(3, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(4, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(5, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(6, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(7, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(8, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]'),
(9, '[[\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"], [\"block\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"ground\", \"ground\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"box\", \"block\"], [\"block\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"ground\", \"ground\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\"], [\"block\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"box\", \"ground\", \"box\", \"box\", \"box\", \"block\"], [\"block\", \"ground\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\", \"ground\", \"block\", \"ground\", \"block\", \"box\", \"block\"], [\"block\", \"ground\", \"box\", \"ground\", \"box\", \"box\", \"ground\", \"ground\", \"box\", \"ground\", \"ground\", \"box\", \"box\", \"ground\", \"block\"], [\"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\", \"block\"]]');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Stages`
--
ALTER TABLE `Stages`
  ADD PRIMARY KEY (`id_stage`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `Stages`
--
ALTER TABLE `Stages`
  MODIFY `id_stage` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
