#!/usr/bin/python
# -*- coding: utf-8 -*-

WINDOW_SIZE = (960, 960)
COLOR_BACKGROUND = (128, 0, 128)
COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
FPS = 60.0
MENU_BACKGROUND_COLOR = (228, 55, 36)
BOMB = "sprites/Bomb/Bomb_f01.png"
BOMBERMAN_RIGHT = "sprites/Bomberman/Right/Bman_R_f00.png"
BOMBERMAN_LEFT = "sprites/Bomberman/Left/Bman_L_f00.png"
BOMBERMAN_FRONT = "sprites/Bomberman/Front/Bman_F_f00.png"
BOMBERMAN_BACK = "sprites/Bomberman/Back/Bman_B_f00.png"
CREEP_RIGHT = "sprites/Creep/Right/Creep_R_f00.png"
CREEP_LEFT = "sprites/Creep/Left/Creep_L_f00.png"
CREEP_FRONT = "sprites/Creep/Front/Creep_F_f00.png"
CREEP_BACK = "sprites/Creep/Back/Creep_B_f00.png"
UNIT_GROUND = "sprites/Blocks/BackgroundTile.png"
UNIT_BLOCK = "sprites/Blocks/SolidBlock.png"
UNIT_BOX = "sprites/Blocks/ExplodableBlock.png"
UNIT_PORTAL = "sprites/Blocks/Portal.png"
X_MIN = 0
X_MAX = 15
Y_MIN = 0
Y_MAX = 15
SIZE_UNIT = 64
BOMBERMAN_INITIAL_POSITION_X = 1
BOMBERMAN_INITIAL_POSITION_Y = 1
WINDOW_CAPTION = "James Bomb"
DEFAULT_HP_BOMBERMAN = 3
DEFAULT_XP_BOMBERMAN = 0
DEFAULT_HP_CREEP = 1
DEFAULT_XP_CREEP = 0
DEFAULT_BOMB_AMOUNT = 1
DEFAULT_BOMB_SCOPE = 1
MAX_BOMB_AMOUNT = 10
DEFAULT_CREEP_AMOUNT = 3
SECOND = 1000 # une seconde
